### PR TITLE
update dependency 'lwip' for Node 6.x

### PR DESCRIPTION
**Pull request by narr**
HI, @kezoo. Because of 'lwip' dependency , I couldn't install this plugin with Node 6.x - https://github.com/EyalAr/lwip/issues/249 and plz update the dependency or merge my PR. Thanks.

### CODE REVIEW

**Comment by klaussilveira** [comment]
Any updates on this? @kezoo

**Comment by acaw-linio** [comment]
Same problem here, any news @kezoo ?

**Comment by tavofuentes** [comment]
I have the same issue.

**Comment by mathop** [comment]
Same here. ping @kezoo

**Comment by kezoo** [comment]
Merge now, sorry for being inactive

**Pull request merged**
